version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'Ticketing_DB'
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    volumes:
      - '.data:/var/lib/postgresql/data'
